[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
upload_speed = 921600
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = partitions_hub.csv
lib_deps =
  esphome/ESPAsyncWebServer-esphome @ ^3.3.0
  knolleary/PubSubClient @ ^2.8
