[env:esp32dev]
platform = espressif32
; board = esp32dev
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.filesystem = littlefs
board_build.partitions = noota4.csv
lib_deps =
  sensirion/Sensirion I2C SCD4x@^1.1.0
build_flags = 
   -D ARDUINO_USB_MODE=1
   -D ARDUINO_USB_CDC_ON_BOOT=1
